### ISSUE TITLE
Cannot install on Raspberry Pi 3

### ISSUE THREAD

**Issue by The-Alchemist** [Wyliodrin/WyliodrinSTUDIO#19]
## Screenshot

![w studio-cannot install](https://cloud.githubusercontent.com/assets/812287/17633123/ca055dd2-6099-11e6-8272-8e14928ce8b5.png)

Strange, because I can SSH in.
## Specs
- Raspberry Pi 3
- Raspbian Jessie Lite

**Comment by alexandruradovici** [comment]
Should be fixed
