### ISSUE TITLE
misleading examples projects for Raspberry PI

### ISSUE THREAD

**Issue by The-Alchemist** [Wyliodrin/WyliodrinSTUDIO#20]
I have a Raspberry Pi 3 connected, but some of the projects listed seem to be Arduino-only.  It's pretty misleading:

![image](https://cloud.githubusercontent.com/assets/812287/18153613/a3e2ab2c-6fcc-11e6-8006-c428cdf31a45.png)

**Comment by alexandruradovici** [comment]
Hi,

We are working on a new example system, much more intuitive. It will also allow you to load new example sources.

You can take a look if you download and build it.

**Comment by The-Alchemist** [comment]
@alexandruradovici : thanks!  you mean it's in master right now?

**Comment by alexandruradovici** [comment]
The new system yes, we are working on the example projects.

Alexandru
