### ISSUE TITLE
Refresh on File Manager page refreezes app

### ISSUE THREAD

**Issue by The-Alchemist** [Wyliodrin/WyliodrinSTUDIO#21]
- Raspberry Pi 3, connected via WiFi
- WyliodrinSTUDIO running as Chrome App
- shell works fine, running project works fine
- but hitting Refresh on the File Manager always freezes the app, instantly

**Comment by serban-razvan** [comment]
Hello and thank you for taking the time to file this issue.

May I ask for supplementary information? How were you able to access the File Manager when running as Chrome App (as far as we know, the button stays hidden when connected as a Chrome App) ?

**Comment by The-Alchemist** [comment]
I'll send the screenshot after this weekend, but I'm pretty sure the File
Manager is available on the Chrome app.

**Comment by serban-razvan** [comment]
Still waiting for that screenshot

**Comment by The-Alchemist** [comment]
@serban-razvan : Sorry for the delay.  Screencast available at https://www.youtube.com/watch?v=QiyuB-ZJx1g

**Comment by The-Alchemist** [comment]
Running ``sudo apt-get update && sudo apt-get upgrade`` seems to fix the issue.

So the image ``wyliodrin_raspberry_pi_2016_06_22.img`` is the one that has this bug, I believe.

**Comment by serban-razvan** [comment]
Closed
