### ISSUE TITLE
We should change the flow of the create new project operation

### ISSUE THREAD

**Issue by oviska** [Wyliodrin/WyliodrinSTUDIO#30]
### Description

Currently when a user tries to create a new project he names the project and has to click the newly created project again in order to open it.

Maybe the project should be opened automatically when is created.

### Steps to Reproduce

**Expected behavior:** 
1. Click on the Create new application
2. Enter application name
3. New application is created and opened

**Actual behavior:** 
1. Click on the Create new application
2. Enter application name
3. New application is created and opened
4. Click on the new application from the list
5. The application is opened

**Comment by alexandruradovici** [comment]
I agree this would be easier for users.
