### ISSUE TITLE
Option to shutdown the board

### ISSUE THREAD

**Issue by pedrohenriquegomes** [Wyliodrin/WyliodrinSTUDIO#34]
### Description

This is a feature that would be interesting for students. 
If there is any way of shutting down the Raspberry Pi board, it would be nice. We can always do that on the Shell tab, but if the Disconnect button also allowed us to shutdown down the board, maybe it would be useful

**Comment by alexandruradovici** [comment]
We should add a library to wylidorin/wylidorin-app-server that runs a shell command and use this to power off the board off.

**Comment by oviska** [comment]
Maybe we could open a popup when clicking disconnect, and give the users several options like: disconnect the board, disconnect and power off the board, etc..

**Comment by alexandruradovici** [comment]
Yes, I agree. Also add an option to reboot the device.

**Comment by serban-razvan** [comment]
Functionality added, needs design in dialogs/disconnect.html view

**Comment by oviska** [comment]
Done
