### ISSUE TITLE
Display the author in the example dialog

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#35]
### Description

The example.json file should contain an author field. This should be displayed in the load example dialog.

### Steps to Reproduce

1. Go to Project
2. Select Load an example
3. Write Wyliodrin/WyliodrinStudioExample in the repository field
4. Display the author besides the other data for each example

**Comment by serban-razvan** [comment]
Where the author should be taken from?

If the projects from Github must be modified, where should the author field be added?

**Comment by serban-razvan** [comment]
My mistake.
Added, should be moved to a more visual appealing place

**Comment by oviska** [comment]
Done!
