### ISSUE TITLE
Add option to save password when connecting to board

### ISSUE THREAD

**Issue by pedrohenriquegomes** [Wyliodrin/WyliodrinSTUDIO#38]
### Description

This is a feature that students suggested: a way of saving the user and password when connecting to the boards. Currently only the user is saved.

**Comment by alexandruradovici** [comment]
The user is saved right now for each device until the user restarts Wyliodrin STUDIO. Your suggestion would be to save the password like the username?

**Comment by pedrohenriquegomes** [comment]
Yes, maybe link the password to the board name and every time the user wants to connect to a given board the user and password is filled automatically. It makes sense in a scenario where each student always connect to the same board.
This could cause security issues, so has to be better considered.

**Comment by alexandruradovici** [comment]
If we store it until Wyliodrin STUDIO is running, I think it should be fine.
