### ISSUE TITLE
Firmware examples

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#39]
### Description

Firmware editors should have an example button. This would open the window with firmware example and the user would be able to load an example firmware.

### Steps to Reproduce

1. Select a firmware
2. Click a "load example" button 
3. Select a firmware (for the specific firmware type)
4. Replace the current firmware in the editor with that firmware

The firmware can have multiple files. They are stored in embedded/example/firmware/firmware_type.

**Comment by oviska** [comment]
Added button, it needs added functionality now.
