### ISSUE TITLE
Hide run make messages

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#47]
### Description

When running a project, the make commands should be hidden so users can see only the messages that their programs show.

### Steps to Reproduce

1. Open a project
2. Press run
3. Open the console

**Expected behavior:** Only messages shown by the user program or errors should be shown

**Actual behavior:** make commands are shown besides the program messages and the errors

**Comment by serban-razvan** [comment]
Closed in Wyliodrin/wyliodrin-app-server@e27b12af7cd251cbb61809001dbf1914bd7e37ab
