### ISSUE TITLE
Learning Wyliodrin STUDIO

### ISSUE THREAD

**Issue by Henrietta1989** [Wyliodrin/WyliodrinSTUDIO#48]
Are you planning to support ODROID?

Where i can find apps which others have created with Wyliodrin STUDIO? So i can learn more how to do visual programming with Wyliodrin STUDIO.

If i have installed STUDIO with this script:

[https://github.com/Wyliodrin/WyliodrinSTUDIO/blob/master/source/embedded/install/raspberrypi.sh](https://github.com/Wyliodrin/WyliodrinSTUDIO/blob/master/source/embedded/install/raspberrypi.sh)

Can i still use these instructions to get the most latest version of STUDIO?

```
git clone https://www.github.com/Wyliodrin/WyliodrinSTUDIO
cd WyliodrinSTUDIO
yarn # npm install works slow
patch node_modules/highcharts-ng/dist/highcharts-ng.js patches/highcharts-ng.patch
patch node_modules/angular-tree-control/css/tree-control-attribute.css patches/tree-control-attribute.patch
patch node_modules/marked/lib/marked.js patches/marked.patch
grunt
```

**Comment by alexandruradovici** [comment]
We would like to be able to support as many devices as possible, but we have limited resources available. 

As Wyliodrin STUDIO is open source, if you find anybody that would be able to make small changes to javascript code, we can offer all the support. We will post a wiki on how to port Wyliodrin STUDIO to other devices.

Yes, the instructions are fine, you should be able to use it. If there are any issues, just let us know and we will be happy to assist you.
