### ISSUE TITLE
Visual and streams projects should have the project tree collapsed

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#53]
### Description

As visual projects are for beginners, maybe they should be loaded with the tree project collapsed. For other project types, the tree should be expanded when a project is loaded.

For streams projects, usually they would have a single file, so maybe we should apply the same.

**Comment by oviska** [comment]
Maybe we should not have a file tree manager at all on visual programming projects. Begginers will never use it.

**Comment by alexandruradovici** [comment]
You might use it to add firmware (is you use the Arduino features) or add file for web servers.

**Comment by alexandruradovici** [comment]
Razvan, can you implement this?
