### ISSUE TITLE
Shell has a wrong evironment

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#54]
### Description

When opening a new shell, the environment is wrong.

HOME is /home/pi instead of /wyliodrin
NODE_PATH is not set

### Steps to Reproduce

1. Connect to a board
2. Open a shell
3. pwd

**Expected behavior:** Should print /wyliodrin

**Actual behavior:** prints /home/pi

**Comment by serban-razvan** [comment]
Shouldn't be set to /home/pi?

**Comment by alexandruradovici** [comment]
It should be /wyliodrin, this is in the
/etc/wyliodrin/settings_raspberrypi.json file.

I think you can inherit it frim wyliodrin-app-server.

Alexandru
