### ISSUE TITLE
Scroll bar appears on the rename projects dialog

### ISSUE THREAD

**Issue by serban-razvan** [Wyliodrin/WyliodrinSTUDIO#55]
### Description

Scroll bar appears on the rename projects dialog

### Steps to Reproduce

1. Create project
2. In the projects page, click rename

**Expected behavior:** Dialog without scroll bar appears

**Actual behavior:** Dialog with scroll bar appears

**Reproduces how often:** always

**Comment by oviska** [comment]
fixed
