### ISSUE TITLE
Connection status overlaps with OS image

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#56]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Restarted Chrome (close all Chrome windows and apps)
    * Have the latest Wyliodrin STUDIO version (10.9)

### Description

The connection status overlaps with the OS image

### Steps to Reproduce

1. Select the French language
2. Click Connect
3. Select IP Address
4. Enter an address that does not exist

![screen shot 2017-02-22 at 00 36 43](https://cloud.githubusercontent.com/assets/2838177/23188331/02bc6e1e-f897-11e6-965c-cf6bdbc37bfc.png)

**Comment by serban-razvan** [comment]
Closed with #96
