### ISSUE TITLE
A saved icon when a file is saved

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#62]
### Description

A request that we got was to have an icon or text that would show if a file is saved. Files are saved each time a key is pressed. 
### Steps to Reproduce

1. Open a project
2. Select a file
3. Type some text

**Expected behavior:** an icon should show if the file is saved

**Actual behavior:** The file is saved but the user cannot see the action happening

**Comment by alexandruradovici** [comment]
We should use the async version of storeProject in ProjectController.

**Comment by oviska** [comment]
Old issue, il inchid
