### ISSUE TITLE
Add some information to CONTRIBUTING

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#64]
### Description

It would be a good idea to add to the [CONTRIBUTING.md](https://github.com/Wyliodrin/WyliodrinSTUDIO/blob/master/CONTRIBUTING.md) file the fact that people should 

1. fork the repository
2. make a new branch for a feature or bugfix
3. merge the branch back
4. make a pull request

**Comment by alicesuiu** [comment]
I will do this.
