### ISSUE TITLE
Verify translation messages id

### ISSUE THREAD

**Issue by alexandruradovici** [Wyliodrin/WyliodrinSTUDIO#65]
### Description

Translations are json files containing an ID for every text. The English file is the reference, but other language files might not have all the IDs. This is not visible for the user, as the English text will be displayed if the ID is not in the specified language file.

A javascript script that would verify that all IDs from the English file are present in the other files would increase translation fullness.

**Comment by andadrn** [comment]
I will do this.

**Comment by alexandruradovici** [comment]
Anda, any news here with the new pull request?

**Comment by andadrn** [comment]
Hi, sorry for the late reply. I'm working on it.
