### ISSUE TITLE
No translation for the menu ( for downloading an image)

### ISSUE THREAD

**Issue by Sorina14** [Wyliodrin/WyliodrinSTUDIO#91]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Restarted Chrome (close all Chrome windows and apps)
    * Have the latest Wyliodrin STUDIO version (10.9)

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Version

Wyliodrin STUDIO:

Chrome browser: 

OS name:
OS version: 

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
![screenshot from 2017-11-01 18 01 48](https://user-images.githubusercontent.com/11373231/32284280-6712ef0a-bf2f-11e7-9563-0d9acb9b07fd.png)

**Comment by serban-razvan** [comment]
Closed with #95
